{
    "openapi": "3.0.1",
    "info": {
        "title": "Energy API",
        "description": "This API allows access to energy and further electrification information",
        "contact": {},
        "version": "1.0"
    },
    "servers": [
        {
            "url": "https://api.volvocars.com/energy"
        }
    ],
    "paths": {
        "/v1/vehicles/{vin}/recharge-status": {
            "get": {
                "tags": [
                    "Recharge status"
                ],
                "summary": "Get latest recharge information",
                "description": "Vehicle's latest recharge information",
                "operationId": "GetRechargeStatus",
                "parameters": [
                    {
                        "name": "vin",
                        "in": "path",
                        "description": "Vehicle identifier (VIN)",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "vcc-api-operationId",
                        "in": "header",
                        "description": "A transaction unique id which can be used do identify the transaction in integrated systems",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/vnd.volvocars.api.energy.vehicledata.v1+json": {
                                "schema": {
                                    "$ref": "#/components/schemas/RechargeStatusResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "data": {
                                        "batteryChargeLevel": {
                                            "value": "string",
                                            "timestamp": "string",
                                            "unit": "string"
                                        },
                                        "electricRange": {
                                            "value": "string",
                                            "timestamp": "string",
                                            "unit": "string"
                                        },
                                        "estimatedChargingTime": {
                                            "value": "string",
                                            "timestamp": "string",
                                            "unit": "string"
                                        },
                                        "chargingConnectionStatus": {
                                            "value": "string",
                                            "timestamp": "string"
                                        },
                                        "chargingSystemStatus": {
                                            "value": "string",
                                            "timestamp": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Request contains an unaccepted input",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "Resource forbidden",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/vehicles/{vin}/recharge-status/battery-charge-level": {
            "get": {
                "tags": [
                    "Battery charge level"
                ],
                "summary": "Get battery charge level",
                "description": "Vehicle's latest battery charge level in percentage",
                "operationId": "GetBatteryChargeLevel",
                "parameters": [
                    {
                        "name": "vin",
                        "in": "path",
                        "description": "Vehicle identifier (VIN)",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "vcc-api-operationId",
                        "in": "header",
                        "description": "A transaction unique id which can be used do identify the transaction in integrated systems",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/vnd.volvocars.api.energy.vehicledata.v1+json": {
                                "schema": {
                                    "$ref": "#/components/schemas/BatteryChargeLevelResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "data": {
                                        "batteryChargeLevel": {
                                            "value": "string",
                                            "timestamp": "string",
                                            "unit": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Request contains an unaccepted input",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "Resource forbidden",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/vehicles/{vin}/recharge-status/electric-range": {
            "get": {
                "tags": [
                    "Electric range"
                ],
                "summary": "Get electric range",
                "description": "Vehicle's latest electric range in kilometers",
                "operationId": "GetElectricRange",
                "parameters": [
                    {
                        "name": "vin",
                        "in": "path",
                        "description": "Vehicle identifier (VIN)",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "vcc-api-operationId",
                        "in": "header",
                        "description": "A transaction unique id which can be used do identify the transaction in integrated systems",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/vnd.volvocars.api.energy.vehicledata.v1+json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ElectricRangeResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "data": {
                                        "electricRange": {
                                            "value": "string",
                                            "timestamp": "string",
                                            "unit": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Request contains an unaccepted input",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "Resource forbidden",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/vehicles/{vin}/recharge-status/estimated-charging-time": {
            "get": {
                "tags": [
                    "Estimated charging time"
                ],
                "summary": "Get estimated charging time",
                "description": "Vehicle's latest estimated charging time in minutes",
                "operationId": "GetEstimatedChargingTime",
                "parameters": [
                    {
                        "name": "vin",
                        "in": "path",
                        "description": "Vehicle identifier (VIN)",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "vcc-api-operationId",
                        "in": "header",
                        "description": "A transaction unique id which can be used do identify the transaction in integrated systems",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/vnd.volvocars.api.energy.vehicledata.v1+json": {
                                "schema": {
                                    "$ref": "#/components/schemas/EstimatedChargingTimeResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "data": {
                                        "estimatedChargingTime": {
                                            "value": "string",
                                            "timestamp": "string",
                                            "unit": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Request contains an unaccepted input",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "Resource forbidden",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/vehicles/{vin}/recharge-status/charging-connection-status": {
            "get": {
                "tags": [
                    "Charging connection status"
                ],
                "summary": "Get charging connection status",
                "description": "Vehicle's latest charging connection status",
                "operationId": "GetChargingConnectionStatus",
                "parameters": [
                    {
                        "name": "vin",
                        "in": "path",
                        "description": "Vehicle identifier (VIN)",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "vcc-api-operationId",
                        "in": "header",
                        "description": "A transaction unique id which can be used do identify the transaction in integrated systems",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/vnd.volvocars.api.energy.vehicledata.v1+json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ChargingConnectionStatusResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "data": {
                                        "chargingConnectionStatus": {
                                            "value": "string",
                                            "timestamp": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Request contains an unaccepted input",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "Resource forbidden",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/vehicles/{vin}/recharge-status/charging-system-status": {
            "get": {
                "tags": [
                    "Charging system status"
                ],
                "summary": "Get charging system status",
                "description": "Vehicle's latest charging system status",
                "operationId": "GetChargingSystemStatus",
                "parameters": [
                    {
                        "name": "vin",
                        "in": "path",
                        "description": "Vehicle identifier (VIN)",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "vcc-api-operationId",
                        "in": "header",
                        "description": "A transaction unique id which can be used do identify the transaction in integrated systems",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/vnd.volvocars.api.energy.vehicledata.v1+json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ChargingSystemStatusResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "data": {
                                        "chargingSystemStatus": {
                                            "value": "string",
                                            "timestamp": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Request contains an unaccepted input",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "Resource forbidden",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "415": {
                        "description": "Unsupported Media Type",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                },
                                "example": {
                                    "status": 0,
                                    "operationId": "string",
                                    "error": {
                                        "message": "string",
                                        "description": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Error": {
                "type": "object",
                "properties": {
                    "message": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    }
                }
            },
            "ErrorResponse": {
                "type": "object",
                "properties": {
                    "status": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "operationId": {
                        "type": "string"
                    },
                    "error": {
                        "$ref": "#/components/schemas/Error"
                    }
                }
            },
            "RInstance": {
                "type": "object",
                "properties": {
                    "value": {
                        "type": "string"
                    },
                    "timestamp": {
                        "type": "string",
                        "format": "date-time"
                    }
                }
            },
            "RInstanceWithUnit": {
                "type": "object",
                "properties": {
                    "value": {
                        "type": "string"
                    },
                    "timestamp": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "unit": {
                        "type": "string"
                    }
                }
            },
            "RechargeStatus": {
                "type": "object",
                "properties": {
                    "batteryChargeLevel": {
                        "$ref": "#/components/schemas/RInstanceWithUnit"
                    },
                    "electricRange": {
                        "$ref": "#/components/schemas/RInstanceWithUnit"
                    },
                    "estimatedChargingTime": {
                        "$ref": "#/components/schemas/RInstanceWithUnit"
                    },
                    "chargingConnectionStatus": {
                        "$ref": "#/components/schemas/RInstance"
                    },
                    "chargingSystemStatus": {
                        "$ref": "#/components/schemas/RInstance"
                    }
                }
            },
            "RechargeStatusResponse": {
                "type": "object",
                "properties": {
                    "status": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "operationId": {
                        "type": "string"
                    },
                    "data": {
                        "$ref": "#/components/schemas/RechargeStatus"
                    }
                }
            },
            "EstimatedChargingTime": {
                "type": "object",
                "properties": {
                    "estimatedChargingTime": {
                        "$ref": "#/components/schemas/RInstanceWithUnit"
                    }
                }
            },
            "EstimatedChargingTimeResponse": {
                "type": "object",
                "properties": {
                    "status": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "operationId": {
                        "type": "string"
                    },
                    "data": {
                        "$ref": "#/components/schemas/EstimatedChargingTime"
                    }
                }
            },
            "ElectricRange": {
                "type": "object",
                "properties": {
                    "electricRange": {
                        "$ref": "#/components/schemas/RInstanceWithUnit"
                    }
                }
            },
            "ElectricRangeResponse": {
                "type": "object",
                "properties": {
                    "status": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "operationId": {
                        "type": "string"
                    },
                    "data": {
                        "$ref": "#/components/schemas/ElectricRange"
                    }
                }
            },
            "ChargingSystem": {
                "type": "object",
                "properties": {
                    "chargingSystemStatus": {
                        "$ref": "#/components/schemas/RInstance"
                    }
                }
            },
            "ChargingSystemStatusResponse": {
                "type": "object",
                "properties": {
                    "status": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "operationId": {
                        "type": "string"
                    },
                    "data": {
                        "$ref": "#/components/schemas/ChargingSystem"
                    }
                }
            },
            "ChargingConnection": {
                "type": "object",
                "properties": {
                    "chargingConnectionStatus": {
                        "$ref": "#/components/schemas/RInstance"
                    }
                }
            },
            "ChargingConnectionStatusResponse": {
                "type": "object",
                "properties": {
                    "status": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "operationId": {
                        "type": "string"
                    },
                    "data": {
                        "$ref": "#/components/schemas/ChargingConnection"
                    }
                }
            },
            "BatteryCharge": {
                "type": "object",
                "properties": {
                    "batteryChargeLevel": {
                        "$ref": "#/components/schemas/RInstanceWithUnit"
                    }
                }
            },
            "BatteryChargeLevelResponse": {
                "type": "object",
                "properties": {
                    "status": {
                        "type": "integer",
                        "format": "int32"
                    },
                    "operationId": {
                        "type": "string"
                    },
                    "data": {
                        "$ref": "#/components/schemas/BatteryCharge"
                    }
                }
            }
        },
        "securitySchemes": {
            "apiKeyHeader": {
                "type": "apiKey",
                "name": "vcc-api-key",
                "in": "header",
                "description": "Your application’s VCC API Key."
            },
            "accessToken": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "description": "The access token issued by Volvo ID identity system."
            }
        }
    },
    "security": [
        {
            "apiKeyHeader": []
        },
        {
            "accessToken": []
        }
    ]
}
